export const SEARCHITEMS_LOADING = "SEARCHITEMS_LOADING";
export const SEARCHITEMS_FAILED = "SEARCHITEMS_FAILED";
export const ADD_SEARCHITEMS = "ADD_SEARCHITEMS";

export const ADD_FAVORITES = "ADD_FAVORITES";
export const FAVORITES_FAILED = "FAVORITES_FAILED";
export const FAVORITES_LOADING = "FAVORITES_LOADING";

export const USER_LOADING = "USER_LOADING";
export const ADD_USER = "ADD_USER";
export const USER_FAILED = "USER_FAILED";
